/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jamcity;

import org.checkerframework.checker.units.qual.C;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void test1() {
        Road r = new Road(100);
        r.addCar(new Car(3, 99));
        r.addCar(new Car(40, 75));
        r.addCar(new Car(20,99));
        r.addCar(new Car(28,76));
        r.addCar(new Car(1,100));



    }
}
