/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jamcity;

public class App {
    public static void main(String[] args) {

        Road r = new Road(100);
        Car[] cars = new Car[5];
        

    }
}
