/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"

std::string Test::Greeter::greeting() {
}

int main () {
    return 0;
}
